version: "3.5"
services:
  kapacitor:
    image: kapacitor:1.5.3-alpine
    hostname: kapacitor
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    # ports:
    #   - "9092:9092"
    volumes:
      - "/var/docker/kapacitor/data:/var/lib/kapacitor"
      - "/var/docker/kapacitor/conf/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - online
networks:
  online:
    external: true
    name: online
